### ISSUE TITLE
the speed issue

### ISSUE THREAD

**Issue by cp149** [unrelatedlabs/SpellingCorrector-Java8#1]
hi
just read your code,it's cool. the only issue of speed, change  function correct to this,on my pc, it run in 6s

Optional<String> e1 = known( edits1(word)).max( (a,b) -> dict.get(a) - dict.get(b) );
		if(e1.isPresent())return dict.containsKey(word) ? word : e1.get();
        Optional<String> e2 = known(edits1(word).map( (w2)->edits1(w2) ).flatMap((x)->x)).max( (a,b) -> dict.get(a) - dict.get(b) );
        return (e2.isPresent() ? e2.get() : word);

**Comment by unrelatedlabs** [comment]
Cool, Do you want to make a pull request?

**Comment by cp149** [comment]
sure
